apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: superset-ingress
  namespace: superset
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: superset.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: superset-service
                port:
                  number: 8088
  tls:
    - hosts:
        - superset.example.com
      secretName: superset-tls-secret