apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
  namespace: superset
type: Opaque
stringData:
  database-uri: "<set-in-key-vault>"
  redis-url: "<set-in-key-vault>"
  secret-key: "<set-in-key-vault>"